services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./my-php-app.conf:/etc/apache2/sites-available/my-php-app.conf
    ports:
      - "9000:80"
    environment:
      DB_HOST: database-1.c1vao1bbmxs8.us-west-2.rds.amazonaws.com
      DB_NAME: dvd_web
      DB_USER: admin
      DB_PASSWORD: 0333342584
networks:
  app-network:
    driver: bridge